// Generated by https://quicktype.io

export interface Asset {
  collection: Collection
}

export interface Collection {
  version: string
  href: string
  items: Item[]
}

export interface Item {
  href: string
}
