// Generated by https://quicktype.io

export interface SearchResult {
    collection: Collection;
}

export interface Collection {
    version:  string;
    href:     string;
    items:    Item[];
    metadata: Metadata;
    links:    CollectionLink[];
}

export interface Item {
    href:   string;
    data:   Datum[];
    links?: ItemLink[];
}

export interface Datum {
    description:        string;
    title:              string;
    photographer?:      Photographer;
    location?:          Location;
    nasa_id:            string;
    date_created:       string;
    keywords:           string[];
    media_type:         MediaType;
    center:             Center;
    album?:             string[];
    description_508?:   string;
    secondary_creator?: string;
}

export enum Center {
    Hq = "HQ",
    Jpl = "JPL",
    Jsc = "JSC",
}

export enum Location {
    JPLPasadenaCalifornia = "JPL - Pasadena, California",
    JetPropulsionLaboratoryMars = "Jet Propulsion Laboratory/Mars",
    JetPropulsionLaboratoryPasadenaCA = "Jet Propulsion Laboratory, Pasadena, CA",
    JezeroCraterMars = "Jezero Crater, Mars",
    MarsPAUSA = "Mars, PA, USA",
}

export enum MediaType {
    Audio = "audio",
    Image = "image",
    Video = "video",
}

export enum Photographer {
    NASABillIngalls = "NASA/Bill Ingalls",
}

export interface ItemLink {
    href:    string;
    rel:     Rel;
    render?: MediaType;
}

export enum Rel {
    Captions = "captions",
    Preview = "preview",
}

export interface CollectionLink {
    rel:    string;
    prompt: string;
    href:   string;
}

export interface Metadata {
    total_hits: number;
}
